// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graph.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_graph_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_graph_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_graph_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_graph_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_graph_2eproto;
namespace seegnify {
namespace graph {
class ErrorResponse;
class ErrorResponseDefaultTypeInternal;
extern ErrorResponseDefaultTypeInternal _ErrorResponse_default_instance_;
class GetWeights;
class GetWeightsDefaultTypeInternal;
extern GetWeightsDefaultTypeInternal _GetWeights_default_instance_;
class GetWeightsResponse;
class GetWeightsResponseDefaultTypeInternal;
extern GetWeightsResponseDefaultTypeInternal _GetWeightsResponse_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class SetWeights;
class SetWeightsDefaultTypeInternal;
extern SetWeightsDefaultTypeInternal _SetWeights_default_instance_;
class SuccessResponse;
class SuccessResponseDefaultTypeInternal;
extern SuccessResponseDefaultTypeInternal _SuccessResponse_default_instance_;
class UpdWeights;
class UpdWeightsDefaultTypeInternal;
extern UpdWeightsDefaultTypeInternal _UpdWeights_default_instance_;
}  // namespace graph
}  // namespace seegnify
PROTOBUF_NAMESPACE_OPEN
template<> ::seegnify::graph::ErrorResponse* Arena::CreateMaybeMessage<::seegnify::graph::ErrorResponse>(Arena*);
template<> ::seegnify::graph::GetWeights* Arena::CreateMaybeMessage<::seegnify::graph::GetWeights>(Arena*);
template<> ::seegnify::graph::GetWeightsResponse* Arena::CreateMaybeMessage<::seegnify::graph::GetWeightsResponse>(Arena*);
template<> ::seegnify::graph::Request* Arena::CreateMaybeMessage<::seegnify::graph::Request>(Arena*);
template<> ::seegnify::graph::Response* Arena::CreateMaybeMessage<::seegnify::graph::Response>(Arena*);
template<> ::seegnify::graph::SetWeights* Arena::CreateMaybeMessage<::seegnify::graph::SetWeights>(Arena*);
template<> ::seegnify::graph::SuccessResponse* Arena::CreateMaybeMessage<::seegnify::graph::SuccessResponse>(Arena*);
template<> ::seegnify::graph::UpdWeights* Arena::CreateMaybeMessage<::seegnify::graph::UpdWeights>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace seegnify {
namespace graph {

// ===================================================================

class GetWeights PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:seegnify.graph.GetWeights) */ {
 public:
  inline GetWeights() : GetWeights(nullptr) {};
  virtual ~GetWeights();

  GetWeights(const GetWeights& from);
  GetWeights(GetWeights&& from) noexcept
    : GetWeights() {
    *this = ::std::move(from);
  }

  inline GetWeights& operator=(const GetWeights& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetWeights& operator=(GetWeights&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetWeights& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetWeights* internal_default_instance() {
    return reinterpret_cast<const GetWeights*>(
               &_GetWeights_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetWeights& a, GetWeights& b) {
    a.Swap(&b);
  }
  inline void Swap(GetWeights* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetWeights* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetWeights* New() const final {
    return CreateMaybeMessage<GetWeights>(nullptr);
  }

  GetWeights* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetWeights>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetWeights& from);
  void MergeFrom(const GetWeights& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetWeights* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "seegnify.graph.GetWeights";
  }
  protected:
  explicit GetWeights(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_graph_2eproto);
    return ::descriptor_table_graph_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:seegnify.graph.GetWeights)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_graph_2eproto;
};
// -------------------------------------------------------------------

class GetWeightsResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:seegnify.graph.GetWeightsResponse) */ {
 public:
  inline GetWeightsResponse() : GetWeightsResponse(nullptr) {};
  virtual ~GetWeightsResponse();

  GetWeightsResponse(const GetWeightsResponse& from);
  GetWeightsResponse(GetWeightsResponse&& from) noexcept
    : GetWeightsResponse() {
    *this = ::std::move(from);
  }

  inline GetWeightsResponse& operator=(const GetWeightsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetWeightsResponse& operator=(GetWeightsResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetWeightsResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetWeightsResponse* internal_default_instance() {
    return reinterpret_cast<const GetWeightsResponse*>(
               &_GetWeightsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetWeightsResponse& a, GetWeightsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetWeightsResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetWeightsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetWeightsResponse* New() const final {
    return CreateMaybeMessage<GetWeightsResponse>(nullptr);
  }

  GetWeightsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetWeightsResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetWeightsResponse& from);
  void MergeFrom(const GetWeightsResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetWeightsResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "seegnify.graph.GetWeightsResponse";
  }
  protected:
  explicit GetWeightsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_graph_2eproto);
    return ::descriptor_table_graph_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWeightsFieldNumber = 1,
  };
  // required bytes weights = 1;
  bool has_weights() const;
  private:
  bool _internal_has_weights() const;
  public:
  void clear_weights();
  const std::string& weights() const;
  void set_weights(const std::string& value);
  void set_weights(std::string&& value);
  void set_weights(const char* value);
  void set_weights(const void* value, size_t size);
  std::string* mutable_weights();
  std::string* release_weights();
  void set_allocated_weights(std::string* weights);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_weights();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_weights(
      std::string* weights);
  private:
  const std::string& _internal_weights() const;
  void _internal_set_weights(const std::string& value);
  std::string* _internal_mutable_weights();
  public:

  // @@protoc_insertion_point(class_scope:seegnify.graph.GetWeightsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr weights_;
  friend struct ::TableStruct_graph_2eproto;
};
// -------------------------------------------------------------------

class SetWeights PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:seegnify.graph.SetWeights) */ {
 public:
  inline SetWeights() : SetWeights(nullptr) {};
  virtual ~SetWeights();

  SetWeights(const SetWeights& from);
  SetWeights(SetWeights&& from) noexcept
    : SetWeights() {
    *this = ::std::move(from);
  }

  inline SetWeights& operator=(const SetWeights& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetWeights& operator=(SetWeights&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SetWeights& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SetWeights* internal_default_instance() {
    return reinterpret_cast<const SetWeights*>(
               &_SetWeights_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SetWeights& a, SetWeights& b) {
    a.Swap(&b);
  }
  inline void Swap(SetWeights* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetWeights* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SetWeights* New() const final {
    return CreateMaybeMessage<SetWeights>(nullptr);
  }

  SetWeights* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SetWeights>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SetWeights& from);
  void MergeFrom(const SetWeights& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetWeights* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "seegnify.graph.SetWeights";
  }
  protected:
  explicit SetWeights(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_graph_2eproto);
    return ::descriptor_table_graph_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWeightsFieldNumber = 1,
  };
  // required bytes weights = 1;
  bool has_weights() const;
  private:
  bool _internal_has_weights() const;
  public:
  void clear_weights();
  const std::string& weights() const;
  void set_weights(const std::string& value);
  void set_weights(std::string&& value);
  void set_weights(const char* value);
  void set_weights(const void* value, size_t size);
  std::string* mutable_weights();
  std::string* release_weights();
  void set_allocated_weights(std::string* weights);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_weights();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_weights(
      std::string* weights);
  private:
  const std::string& _internal_weights() const;
  void _internal_set_weights(const std::string& value);
  std::string* _internal_mutable_weights();
  public:

  // @@protoc_insertion_point(class_scope:seegnify.graph.SetWeights)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr weights_;
  friend struct ::TableStruct_graph_2eproto;
};
// -------------------------------------------------------------------

class UpdWeights PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:seegnify.graph.UpdWeights) */ {
 public:
  inline UpdWeights() : UpdWeights(nullptr) {};
  virtual ~UpdWeights();

  UpdWeights(const UpdWeights& from);
  UpdWeights(UpdWeights&& from) noexcept
    : UpdWeights() {
    *this = ::std::move(from);
  }

  inline UpdWeights& operator=(const UpdWeights& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdWeights& operator=(UpdWeights&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UpdWeights& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdWeights* internal_default_instance() {
    return reinterpret_cast<const UpdWeights*>(
               &_UpdWeights_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(UpdWeights& a, UpdWeights& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdWeights* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdWeights* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UpdWeights* New() const final {
    return CreateMaybeMessage<UpdWeights>(nullptr);
  }

  UpdWeights* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UpdWeights>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UpdWeights& from);
  void MergeFrom(const UpdWeights& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdWeights* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "seegnify.graph.UpdWeights";
  }
  protected:
  explicit UpdWeights(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_graph_2eproto);
    return ::descriptor_table_graph_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUpdateFieldNumber = 1,
  };
  // required bytes update = 1;
  bool has_update() const;
  private:
  bool _internal_has_update() const;
  public:
  void clear_update();
  const std::string& update() const;
  void set_update(const std::string& value);
  void set_update(std::string&& value);
  void set_update(const char* value);
  void set_update(const void* value, size_t size);
  std::string* mutable_update();
  std::string* release_update();
  void set_allocated_update(std::string* update);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_update();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_update(
      std::string* update);
  private:
  const std::string& _internal_update() const;
  void _internal_set_update(const std::string& value);
  std::string* _internal_mutable_update();
  public:

  // @@protoc_insertion_point(class_scope:seegnify.graph.UpdWeights)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr update_;
  friend struct ::TableStruct_graph_2eproto;
};
// -------------------------------------------------------------------

class SuccessResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:seegnify.graph.SuccessResponse) */ {
 public:
  inline SuccessResponse() : SuccessResponse(nullptr) {};
  virtual ~SuccessResponse();

  SuccessResponse(const SuccessResponse& from);
  SuccessResponse(SuccessResponse&& from) noexcept
    : SuccessResponse() {
    *this = ::std::move(from);
  }

  inline SuccessResponse& operator=(const SuccessResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SuccessResponse& operator=(SuccessResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SuccessResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SuccessResponse* internal_default_instance() {
    return reinterpret_cast<const SuccessResponse*>(
               &_SuccessResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SuccessResponse& a, SuccessResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SuccessResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SuccessResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SuccessResponse* New() const final {
    return CreateMaybeMessage<SuccessResponse>(nullptr);
  }

  SuccessResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SuccessResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SuccessResponse& from);
  void MergeFrom(const SuccessResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SuccessResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "seegnify.graph.SuccessResponse";
  }
  protected:
  explicit SuccessResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_graph_2eproto);
    return ::descriptor_table_graph_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:seegnify.graph.SuccessResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_graph_2eproto;
};
// -------------------------------------------------------------------

class ErrorResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:seegnify.graph.ErrorResponse) */ {
 public:
  inline ErrorResponse() : ErrorResponse(nullptr) {};
  virtual ~ErrorResponse();

  ErrorResponse(const ErrorResponse& from);
  ErrorResponse(ErrorResponse&& from) noexcept
    : ErrorResponse() {
    *this = ::std::move(from);
  }

  inline ErrorResponse& operator=(const ErrorResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ErrorResponse& operator=(ErrorResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ErrorResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ErrorResponse* internal_default_instance() {
    return reinterpret_cast<const ErrorResponse*>(
               &_ErrorResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ErrorResponse& a, ErrorResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ErrorResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ErrorResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ErrorResponse* New() const final {
    return CreateMaybeMessage<ErrorResponse>(nullptr);
  }

  ErrorResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ErrorResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ErrorResponse& from);
  void MergeFrom(const ErrorResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ErrorResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "seegnify.graph.ErrorResponse";
  }
  protected:
  explicit ErrorResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_graph_2eproto);
    return ::descriptor_table_graph_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // required string message = 2;
  bool has_message() const;
  private:
  bool _internal_has_message() const;
  public:
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // required uint32 status = 1;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  ::PROTOBUF_NAMESPACE_ID::uint32 status() const;
  void set_status(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_status() const;
  void _internal_set_status(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:seegnify.graph.ErrorResponse)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::uint32 status_;
  friend struct ::TableStruct_graph_2eproto;
};
// -------------------------------------------------------------------

class Request PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:seegnify.graph.Request) */ {
 public:
  inline Request() : Request(nullptr) {};
  virtual ~Request();

  Request(const Request& from);
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Request& default_instance();

  enum RequestCase {
    kGetWeights = 10,
    kSetWeights = 11,
    kUpdWeights = 12,
    REQUEST_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Request* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const final {
    return CreateMaybeMessage<Request>(nullptr);
  }

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "seegnify.graph.Request";
  }
  protected:
  explicit Request(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_graph_2eproto);
    return ::descriptor_table_graph_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGetWeightsFieldNumber = 10,
    kSetWeightsFieldNumber = 11,
    kUpdWeightsFieldNumber = 12,
  };
  // .seegnify.graph.GetWeights get_weights = 10;
  bool has_get_weights() const;
  private:
  bool _internal_has_get_weights() const;
  public:
  void clear_get_weights();
  const ::seegnify::graph::GetWeights& get_weights() const;
  ::seegnify::graph::GetWeights* release_get_weights();
  ::seegnify::graph::GetWeights* mutable_get_weights();
  void set_allocated_get_weights(::seegnify::graph::GetWeights* get_weights);
  private:
  const ::seegnify::graph::GetWeights& _internal_get_weights() const;
  ::seegnify::graph::GetWeights* _internal_mutable_get_weights();
  public:
  void unsafe_arena_set_allocated_get_weights(
      ::seegnify::graph::GetWeights* get_weights);
  ::seegnify::graph::GetWeights* unsafe_arena_release_get_weights();

  // .seegnify.graph.SetWeights set_weights = 11;
  bool has_set_weights() const;
  private:
  bool _internal_has_set_weights() const;
  public:
  void clear_set_weights();
  const ::seegnify::graph::SetWeights& set_weights() const;
  ::seegnify::graph::SetWeights* release_set_weights();
  ::seegnify::graph::SetWeights* mutable_set_weights();
  void set_allocated_set_weights(::seegnify::graph::SetWeights* set_weights);
  private:
  const ::seegnify::graph::SetWeights& _internal_set_weights() const;
  ::seegnify::graph::SetWeights* _internal_mutable_set_weights();
  public:
  void unsafe_arena_set_allocated_set_weights(
      ::seegnify::graph::SetWeights* set_weights);
  ::seegnify::graph::SetWeights* unsafe_arena_release_set_weights();

  // .seegnify.graph.UpdWeights upd_weights = 12;
  bool has_upd_weights() const;
  private:
  bool _internal_has_upd_weights() const;
  public:
  void clear_upd_weights();
  const ::seegnify::graph::UpdWeights& upd_weights() const;
  ::seegnify::graph::UpdWeights* release_upd_weights();
  ::seegnify::graph::UpdWeights* mutable_upd_weights();
  void set_allocated_upd_weights(::seegnify::graph::UpdWeights* upd_weights);
  private:
  const ::seegnify::graph::UpdWeights& _internal_upd_weights() const;
  ::seegnify::graph::UpdWeights* _internal_mutable_upd_weights();
  public:
  void unsafe_arena_set_allocated_upd_weights(
      ::seegnify::graph::UpdWeights* upd_weights);
  ::seegnify::graph::UpdWeights* unsafe_arena_release_upd_weights();

  void clear_request();
  RequestCase request_case() const;
  // @@protoc_insertion_point(class_scope:seegnify.graph.Request)
 private:
  class _Internal;
  void set_has_get_weights();
  void set_has_set_weights();
  void set_has_upd_weights();

  inline bool has_request() const;
  inline void clear_has_request();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union RequestUnion {
    RequestUnion() {}
    ::seegnify::graph::GetWeights* get_weights_;
    ::seegnify::graph::SetWeights* set_weights_;
    ::seegnify::graph::UpdWeights* upd_weights_;
  } request_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_graph_2eproto;
};
// -------------------------------------------------------------------

class Response PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:seegnify.graph.Response) */ {
 public:
  inline Response() : Response(nullptr) {};
  virtual ~Response();

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Response& default_instance();

  enum ResponseCase {
    kGetWeights = 11,
    kSuccess = 12,
    kError = 13,
    RESPONSE_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const final {
    return CreateMaybeMessage<Response>(nullptr);
  }

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "seegnify.graph.Response";
  }
  protected:
  explicit Response(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_graph_2eproto);
    return ::descriptor_table_graph_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGetWeightsFieldNumber = 11,
    kSuccessFieldNumber = 12,
    kErrorFieldNumber = 13,
  };
  // .seegnify.graph.GetWeightsResponse get_weights = 11;
  bool has_get_weights() const;
  private:
  bool _internal_has_get_weights() const;
  public:
  void clear_get_weights();
  const ::seegnify::graph::GetWeightsResponse& get_weights() const;
  ::seegnify::graph::GetWeightsResponse* release_get_weights();
  ::seegnify::graph::GetWeightsResponse* mutable_get_weights();
  void set_allocated_get_weights(::seegnify::graph::GetWeightsResponse* get_weights);
  private:
  const ::seegnify::graph::GetWeightsResponse& _internal_get_weights() const;
  ::seegnify::graph::GetWeightsResponse* _internal_mutable_get_weights();
  public:
  void unsafe_arena_set_allocated_get_weights(
      ::seegnify::graph::GetWeightsResponse* get_weights);
  ::seegnify::graph::GetWeightsResponse* unsafe_arena_release_get_weights();

  // .seegnify.graph.SuccessResponse success = 12;
  bool has_success() const;
  private:
  bool _internal_has_success() const;
  public:
  void clear_success();
  const ::seegnify::graph::SuccessResponse& success() const;
  ::seegnify::graph::SuccessResponse* release_success();
  ::seegnify::graph::SuccessResponse* mutable_success();
  void set_allocated_success(::seegnify::graph::SuccessResponse* success);
  private:
  const ::seegnify::graph::SuccessResponse& _internal_success() const;
  ::seegnify::graph::SuccessResponse* _internal_mutable_success();
  public:
  void unsafe_arena_set_allocated_success(
      ::seegnify::graph::SuccessResponse* success);
  ::seegnify::graph::SuccessResponse* unsafe_arena_release_success();

  // .seegnify.graph.ErrorResponse error = 13;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  const ::seegnify::graph::ErrorResponse& error() const;
  ::seegnify::graph::ErrorResponse* release_error();
  ::seegnify::graph::ErrorResponse* mutable_error();
  void set_allocated_error(::seegnify::graph::ErrorResponse* error);
  private:
  const ::seegnify::graph::ErrorResponse& _internal_error() const;
  ::seegnify::graph::ErrorResponse* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::seegnify::graph::ErrorResponse* error);
  ::seegnify::graph::ErrorResponse* unsafe_arena_release_error();

  void clear_response();
  ResponseCase response_case() const;
  // @@protoc_insertion_point(class_scope:seegnify.graph.Response)
 private:
  class _Internal;
  void set_has_get_weights();
  void set_has_success();
  void set_has_error();

  inline bool has_response() const;
  inline void clear_has_response();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union ResponseUnion {
    ResponseUnion() {}
    ::seegnify::graph::GetWeightsResponse* get_weights_;
    ::seegnify::graph::SuccessResponse* success_;
    ::seegnify::graph::ErrorResponse* error_;
  } response_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_graph_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetWeights

// -------------------------------------------------------------------

// GetWeightsResponse

// required bytes weights = 1;
inline bool GetWeightsResponse::_internal_has_weights() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool GetWeightsResponse::has_weights() const {
  return _internal_has_weights();
}
inline void GetWeightsResponse::clear_weights() {
  weights_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& GetWeightsResponse::weights() const {
  // @@protoc_insertion_point(field_get:seegnify.graph.GetWeightsResponse.weights)
  return _internal_weights();
}
inline void GetWeightsResponse::set_weights(const std::string& value) {
  _internal_set_weights(value);
  // @@protoc_insertion_point(field_set:seegnify.graph.GetWeightsResponse.weights)
}
inline std::string* GetWeightsResponse::mutable_weights() {
  // @@protoc_insertion_point(field_mutable:seegnify.graph.GetWeightsResponse.weights)
  return _internal_mutable_weights();
}
inline const std::string& GetWeightsResponse::_internal_weights() const {
  return weights_.Get();
}
inline void GetWeightsResponse::_internal_set_weights(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  weights_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void GetWeightsResponse::set_weights(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  weights_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:seegnify.graph.GetWeightsResponse.weights)
}
inline void GetWeightsResponse::set_weights(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  weights_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:seegnify.graph.GetWeightsResponse.weights)
}
inline void GetWeightsResponse::set_weights(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  weights_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:seegnify.graph.GetWeightsResponse.weights)
}
inline std::string* GetWeightsResponse::_internal_mutable_weights() {
  _has_bits_[0] |= 0x00000001u;
  return weights_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* GetWeightsResponse::release_weights() {
  // @@protoc_insertion_point(field_release:seegnify.graph.GetWeightsResponse.weights)
  if (!_internal_has_weights()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return weights_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void GetWeightsResponse::set_allocated_weights(std::string* weights) {
  if (weights != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  weights_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), weights,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:seegnify.graph.GetWeightsResponse.weights)
}
inline std::string* GetWeightsResponse::unsafe_arena_release_weights() {
  // @@protoc_insertion_point(field_unsafe_arena_release:seegnify.graph.GetWeightsResponse.weights)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return weights_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void GetWeightsResponse::unsafe_arena_set_allocated_weights(
    std::string* weights) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (weights != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  weights_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      weights, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:seegnify.graph.GetWeightsResponse.weights)
}

// -------------------------------------------------------------------

// SetWeights

// required bytes weights = 1;
inline bool SetWeights::_internal_has_weights() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SetWeights::has_weights() const {
  return _internal_has_weights();
}
inline void SetWeights::clear_weights() {
  weights_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SetWeights::weights() const {
  // @@protoc_insertion_point(field_get:seegnify.graph.SetWeights.weights)
  return _internal_weights();
}
inline void SetWeights::set_weights(const std::string& value) {
  _internal_set_weights(value);
  // @@protoc_insertion_point(field_set:seegnify.graph.SetWeights.weights)
}
inline std::string* SetWeights::mutable_weights() {
  // @@protoc_insertion_point(field_mutable:seegnify.graph.SetWeights.weights)
  return _internal_mutable_weights();
}
inline const std::string& SetWeights::_internal_weights() const {
  return weights_.Get();
}
inline void SetWeights::_internal_set_weights(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  weights_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SetWeights::set_weights(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  weights_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:seegnify.graph.SetWeights.weights)
}
inline void SetWeights::set_weights(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  weights_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:seegnify.graph.SetWeights.weights)
}
inline void SetWeights::set_weights(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  weights_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:seegnify.graph.SetWeights.weights)
}
inline std::string* SetWeights::_internal_mutable_weights() {
  _has_bits_[0] |= 0x00000001u;
  return weights_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SetWeights::release_weights() {
  // @@protoc_insertion_point(field_release:seegnify.graph.SetWeights.weights)
  if (!_internal_has_weights()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return weights_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SetWeights::set_allocated_weights(std::string* weights) {
  if (weights != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  weights_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), weights,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:seegnify.graph.SetWeights.weights)
}
inline std::string* SetWeights::unsafe_arena_release_weights() {
  // @@protoc_insertion_point(field_unsafe_arena_release:seegnify.graph.SetWeights.weights)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return weights_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SetWeights::unsafe_arena_set_allocated_weights(
    std::string* weights) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (weights != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  weights_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      weights, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:seegnify.graph.SetWeights.weights)
}

// -------------------------------------------------------------------

// UpdWeights

// required bytes update = 1;
inline bool UpdWeights::_internal_has_update() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool UpdWeights::has_update() const {
  return _internal_has_update();
}
inline void UpdWeights::clear_update() {
  update_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& UpdWeights::update() const {
  // @@protoc_insertion_point(field_get:seegnify.graph.UpdWeights.update)
  return _internal_update();
}
inline void UpdWeights::set_update(const std::string& value) {
  _internal_set_update(value);
  // @@protoc_insertion_point(field_set:seegnify.graph.UpdWeights.update)
}
inline std::string* UpdWeights::mutable_update() {
  // @@protoc_insertion_point(field_mutable:seegnify.graph.UpdWeights.update)
  return _internal_mutable_update();
}
inline const std::string& UpdWeights::_internal_update() const {
  return update_.Get();
}
inline void UpdWeights::_internal_set_update(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  update_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void UpdWeights::set_update(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  update_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:seegnify.graph.UpdWeights.update)
}
inline void UpdWeights::set_update(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  update_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:seegnify.graph.UpdWeights.update)
}
inline void UpdWeights::set_update(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  update_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:seegnify.graph.UpdWeights.update)
}
inline std::string* UpdWeights::_internal_mutable_update() {
  _has_bits_[0] |= 0x00000001u;
  return update_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* UpdWeights::release_update() {
  // @@protoc_insertion_point(field_release:seegnify.graph.UpdWeights.update)
  if (!_internal_has_update()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return update_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UpdWeights::set_allocated_update(std::string* update) {
  if (update != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  update_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), update,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:seegnify.graph.UpdWeights.update)
}
inline std::string* UpdWeights::unsafe_arena_release_update() {
  // @@protoc_insertion_point(field_unsafe_arena_release:seegnify.graph.UpdWeights.update)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return update_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void UpdWeights::unsafe_arena_set_allocated_update(
    std::string* update) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (update != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  update_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      update, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:seegnify.graph.UpdWeights.update)
}

// -------------------------------------------------------------------

// SuccessResponse

// -------------------------------------------------------------------

// ErrorResponse

// required uint32 status = 1;
inline bool ErrorResponse::_internal_has_status() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ErrorResponse::has_status() const {
  return _internal_has_status();
}
inline void ErrorResponse::clear_status() {
  status_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ErrorResponse::_internal_status() const {
  return status_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ErrorResponse::status() const {
  // @@protoc_insertion_point(field_get:seegnify.graph.ErrorResponse.status)
  return _internal_status();
}
inline void ErrorResponse::_internal_set_status(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  status_ = value;
}
inline void ErrorResponse::set_status(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:seegnify.graph.ErrorResponse.status)
}

// required string message = 2;
inline bool ErrorResponse::_internal_has_message() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ErrorResponse::has_message() const {
  return _internal_has_message();
}
inline void ErrorResponse::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ErrorResponse::message() const {
  // @@protoc_insertion_point(field_get:seegnify.graph.ErrorResponse.message)
  return _internal_message();
}
inline void ErrorResponse::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:seegnify.graph.ErrorResponse.message)
}
inline std::string* ErrorResponse::mutable_message() {
  // @@protoc_insertion_point(field_mutable:seegnify.graph.ErrorResponse.message)
  return _internal_mutable_message();
}
inline const std::string& ErrorResponse::_internal_message() const {
  return message_.Get();
}
inline void ErrorResponse::_internal_set_message(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ErrorResponse::set_message(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:seegnify.graph.ErrorResponse.message)
}
inline void ErrorResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:seegnify.graph.ErrorResponse.message)
}
inline void ErrorResponse::set_message(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:seegnify.graph.ErrorResponse.message)
}
inline std::string* ErrorResponse::_internal_mutable_message() {
  _has_bits_[0] |= 0x00000001u;
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ErrorResponse::release_message() {
  // @@protoc_insertion_point(field_release:seegnify.graph.ErrorResponse.message)
  if (!_internal_has_message()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return message_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ErrorResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:seegnify.graph.ErrorResponse.message)
}
inline std::string* ErrorResponse::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:seegnify.graph.ErrorResponse.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ErrorResponse::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:seegnify.graph.ErrorResponse.message)
}

// -------------------------------------------------------------------

// Request

// .seegnify.graph.GetWeights get_weights = 10;
inline bool Request::_internal_has_get_weights() const {
  return request_case() == kGetWeights;
}
inline bool Request::has_get_weights() const {
  return _internal_has_get_weights();
}
inline void Request::set_has_get_weights() {
  _oneof_case_[0] = kGetWeights;
}
inline void Request::clear_get_weights() {
  if (_internal_has_get_weights()) {
    if (GetArena() == nullptr) {
      delete request_.get_weights_;
    }
    clear_has_request();
  }
}
inline ::seegnify::graph::GetWeights* Request::release_get_weights() {
  // @@protoc_insertion_point(field_release:seegnify.graph.Request.get_weights)
  if (_internal_has_get_weights()) {
    clear_has_request();
      ::seegnify::graph::GetWeights* temp = request_.get_weights_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    request_.get_weights_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::seegnify::graph::GetWeights& Request::_internal_get_weights() const {
  return _internal_has_get_weights()
      ? *request_.get_weights_
      : *reinterpret_cast< ::seegnify::graph::GetWeights*>(&::seegnify::graph::_GetWeights_default_instance_);
}
inline const ::seegnify::graph::GetWeights& Request::get_weights() const {
  // @@protoc_insertion_point(field_get:seegnify.graph.Request.get_weights)
  return _internal_get_weights();
}
inline ::seegnify::graph::GetWeights* Request::unsafe_arena_release_get_weights() {
  // @@protoc_insertion_point(field_unsafe_arena_release:seegnify.graph.Request.get_weights)
  if (_internal_has_get_weights()) {
    clear_has_request();
    ::seegnify::graph::GetWeights* temp = request_.get_weights_;
    request_.get_weights_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Request::unsafe_arena_set_allocated_get_weights(::seegnify::graph::GetWeights* get_weights) {
  clear_request();
  if (get_weights) {
    set_has_get_weights();
    request_.get_weights_ = get_weights;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:seegnify.graph.Request.get_weights)
}
inline ::seegnify::graph::GetWeights* Request::_internal_mutable_get_weights() {
  if (!_internal_has_get_weights()) {
    clear_request();
    set_has_get_weights();
    request_.get_weights_ = CreateMaybeMessage< ::seegnify::graph::GetWeights >(GetArena());
  }
  return request_.get_weights_;
}
inline ::seegnify::graph::GetWeights* Request::mutable_get_weights() {
  // @@protoc_insertion_point(field_mutable:seegnify.graph.Request.get_weights)
  return _internal_mutable_get_weights();
}

// .seegnify.graph.SetWeights set_weights = 11;
inline bool Request::_internal_has_set_weights() const {
  return request_case() == kSetWeights;
}
inline bool Request::has_set_weights() const {
  return _internal_has_set_weights();
}
inline void Request::set_has_set_weights() {
  _oneof_case_[0] = kSetWeights;
}
inline void Request::clear_set_weights() {
  if (_internal_has_set_weights()) {
    if (GetArena() == nullptr) {
      delete request_.set_weights_;
    }
    clear_has_request();
  }
}
inline ::seegnify::graph::SetWeights* Request::release_set_weights() {
  // @@protoc_insertion_point(field_release:seegnify.graph.Request.set_weights)
  if (_internal_has_set_weights()) {
    clear_has_request();
      ::seegnify::graph::SetWeights* temp = request_.set_weights_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    request_.set_weights_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::seegnify::graph::SetWeights& Request::_internal_set_weights() const {
  return _internal_has_set_weights()
      ? *request_.set_weights_
      : *reinterpret_cast< ::seegnify::graph::SetWeights*>(&::seegnify::graph::_SetWeights_default_instance_);
}
inline const ::seegnify::graph::SetWeights& Request::set_weights() const {
  // @@protoc_insertion_point(field_get:seegnify.graph.Request.set_weights)
  return _internal_set_weights();
}
inline ::seegnify::graph::SetWeights* Request::unsafe_arena_release_set_weights() {
  // @@protoc_insertion_point(field_unsafe_arena_release:seegnify.graph.Request.set_weights)
  if (_internal_has_set_weights()) {
    clear_has_request();
    ::seegnify::graph::SetWeights* temp = request_.set_weights_;
    request_.set_weights_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Request::unsafe_arena_set_allocated_set_weights(::seegnify::graph::SetWeights* set_weights) {
  clear_request();
  if (set_weights) {
    set_has_set_weights();
    request_.set_weights_ = set_weights;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:seegnify.graph.Request.set_weights)
}
inline ::seegnify::graph::SetWeights* Request::_internal_mutable_set_weights() {
  if (!_internal_has_set_weights()) {
    clear_request();
    set_has_set_weights();
    request_.set_weights_ = CreateMaybeMessage< ::seegnify::graph::SetWeights >(GetArena());
  }
  return request_.set_weights_;
}
inline ::seegnify::graph::SetWeights* Request::mutable_set_weights() {
  // @@protoc_insertion_point(field_mutable:seegnify.graph.Request.set_weights)
  return _internal_mutable_set_weights();
}

// .seegnify.graph.UpdWeights upd_weights = 12;
inline bool Request::_internal_has_upd_weights() const {
  return request_case() == kUpdWeights;
}
inline bool Request::has_upd_weights() const {
  return _internal_has_upd_weights();
}
inline void Request::set_has_upd_weights() {
  _oneof_case_[0] = kUpdWeights;
}
inline void Request::clear_upd_weights() {
  if (_internal_has_upd_weights()) {
    if (GetArena() == nullptr) {
      delete request_.upd_weights_;
    }
    clear_has_request();
  }
}
inline ::seegnify::graph::UpdWeights* Request::release_upd_weights() {
  // @@protoc_insertion_point(field_release:seegnify.graph.Request.upd_weights)
  if (_internal_has_upd_weights()) {
    clear_has_request();
      ::seegnify::graph::UpdWeights* temp = request_.upd_weights_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    request_.upd_weights_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::seegnify::graph::UpdWeights& Request::_internal_upd_weights() const {
  return _internal_has_upd_weights()
      ? *request_.upd_weights_
      : *reinterpret_cast< ::seegnify::graph::UpdWeights*>(&::seegnify::graph::_UpdWeights_default_instance_);
}
inline const ::seegnify::graph::UpdWeights& Request::upd_weights() const {
  // @@protoc_insertion_point(field_get:seegnify.graph.Request.upd_weights)
  return _internal_upd_weights();
}
inline ::seegnify::graph::UpdWeights* Request::unsafe_arena_release_upd_weights() {
  // @@protoc_insertion_point(field_unsafe_arena_release:seegnify.graph.Request.upd_weights)
  if (_internal_has_upd_weights()) {
    clear_has_request();
    ::seegnify::graph::UpdWeights* temp = request_.upd_weights_;
    request_.upd_weights_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Request::unsafe_arena_set_allocated_upd_weights(::seegnify::graph::UpdWeights* upd_weights) {
  clear_request();
  if (upd_weights) {
    set_has_upd_weights();
    request_.upd_weights_ = upd_weights;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:seegnify.graph.Request.upd_weights)
}
inline ::seegnify::graph::UpdWeights* Request::_internal_mutable_upd_weights() {
  if (!_internal_has_upd_weights()) {
    clear_request();
    set_has_upd_weights();
    request_.upd_weights_ = CreateMaybeMessage< ::seegnify::graph::UpdWeights >(GetArena());
  }
  return request_.upd_weights_;
}
inline ::seegnify::graph::UpdWeights* Request::mutable_upd_weights() {
  // @@protoc_insertion_point(field_mutable:seegnify.graph.Request.upd_weights)
  return _internal_mutable_upd_weights();
}

inline bool Request::has_request() const {
  return request_case() != REQUEST_NOT_SET;
}
inline void Request::clear_has_request() {
  _oneof_case_[0] = REQUEST_NOT_SET;
}
inline Request::RequestCase Request::request_case() const {
  return Request::RequestCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Response

// .seegnify.graph.GetWeightsResponse get_weights = 11;
inline bool Response::_internal_has_get_weights() const {
  return response_case() == kGetWeights;
}
inline bool Response::has_get_weights() const {
  return _internal_has_get_weights();
}
inline void Response::set_has_get_weights() {
  _oneof_case_[0] = kGetWeights;
}
inline void Response::clear_get_weights() {
  if (_internal_has_get_weights()) {
    if (GetArena() == nullptr) {
      delete response_.get_weights_;
    }
    clear_has_response();
  }
}
inline ::seegnify::graph::GetWeightsResponse* Response::release_get_weights() {
  // @@protoc_insertion_point(field_release:seegnify.graph.Response.get_weights)
  if (_internal_has_get_weights()) {
    clear_has_response();
      ::seegnify::graph::GetWeightsResponse* temp = response_.get_weights_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    response_.get_weights_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::seegnify::graph::GetWeightsResponse& Response::_internal_get_weights() const {
  return _internal_has_get_weights()
      ? *response_.get_weights_
      : *reinterpret_cast< ::seegnify::graph::GetWeightsResponse*>(&::seegnify::graph::_GetWeightsResponse_default_instance_);
}
inline const ::seegnify::graph::GetWeightsResponse& Response::get_weights() const {
  // @@protoc_insertion_point(field_get:seegnify.graph.Response.get_weights)
  return _internal_get_weights();
}
inline ::seegnify::graph::GetWeightsResponse* Response::unsafe_arena_release_get_weights() {
  // @@protoc_insertion_point(field_unsafe_arena_release:seegnify.graph.Response.get_weights)
  if (_internal_has_get_weights()) {
    clear_has_response();
    ::seegnify::graph::GetWeightsResponse* temp = response_.get_weights_;
    response_.get_weights_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Response::unsafe_arena_set_allocated_get_weights(::seegnify::graph::GetWeightsResponse* get_weights) {
  clear_response();
  if (get_weights) {
    set_has_get_weights();
    response_.get_weights_ = get_weights;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:seegnify.graph.Response.get_weights)
}
inline ::seegnify::graph::GetWeightsResponse* Response::_internal_mutable_get_weights() {
  if (!_internal_has_get_weights()) {
    clear_response();
    set_has_get_weights();
    response_.get_weights_ = CreateMaybeMessage< ::seegnify::graph::GetWeightsResponse >(GetArena());
  }
  return response_.get_weights_;
}
inline ::seegnify::graph::GetWeightsResponse* Response::mutable_get_weights() {
  // @@protoc_insertion_point(field_mutable:seegnify.graph.Response.get_weights)
  return _internal_mutable_get_weights();
}

// .seegnify.graph.SuccessResponse success = 12;
inline bool Response::_internal_has_success() const {
  return response_case() == kSuccess;
}
inline bool Response::has_success() const {
  return _internal_has_success();
}
inline void Response::set_has_success() {
  _oneof_case_[0] = kSuccess;
}
inline void Response::clear_success() {
  if (_internal_has_success()) {
    if (GetArena() == nullptr) {
      delete response_.success_;
    }
    clear_has_response();
  }
}
inline ::seegnify::graph::SuccessResponse* Response::release_success() {
  // @@protoc_insertion_point(field_release:seegnify.graph.Response.success)
  if (_internal_has_success()) {
    clear_has_response();
      ::seegnify::graph::SuccessResponse* temp = response_.success_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    response_.success_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::seegnify::graph::SuccessResponse& Response::_internal_success() const {
  return _internal_has_success()
      ? *response_.success_
      : *reinterpret_cast< ::seegnify::graph::SuccessResponse*>(&::seegnify::graph::_SuccessResponse_default_instance_);
}
inline const ::seegnify::graph::SuccessResponse& Response::success() const {
  // @@protoc_insertion_point(field_get:seegnify.graph.Response.success)
  return _internal_success();
}
inline ::seegnify::graph::SuccessResponse* Response::unsafe_arena_release_success() {
  // @@protoc_insertion_point(field_unsafe_arena_release:seegnify.graph.Response.success)
  if (_internal_has_success()) {
    clear_has_response();
    ::seegnify::graph::SuccessResponse* temp = response_.success_;
    response_.success_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Response::unsafe_arena_set_allocated_success(::seegnify::graph::SuccessResponse* success) {
  clear_response();
  if (success) {
    set_has_success();
    response_.success_ = success;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:seegnify.graph.Response.success)
}
inline ::seegnify::graph::SuccessResponse* Response::_internal_mutable_success() {
  if (!_internal_has_success()) {
    clear_response();
    set_has_success();
    response_.success_ = CreateMaybeMessage< ::seegnify::graph::SuccessResponse >(GetArena());
  }
  return response_.success_;
}
inline ::seegnify::graph::SuccessResponse* Response::mutable_success() {
  // @@protoc_insertion_point(field_mutable:seegnify.graph.Response.success)
  return _internal_mutable_success();
}

// .seegnify.graph.ErrorResponse error = 13;
inline bool Response::_internal_has_error() const {
  return response_case() == kError;
}
inline bool Response::has_error() const {
  return _internal_has_error();
}
inline void Response::set_has_error() {
  _oneof_case_[0] = kError;
}
inline void Response::clear_error() {
  if (_internal_has_error()) {
    if (GetArena() == nullptr) {
      delete response_.error_;
    }
    clear_has_response();
  }
}
inline ::seegnify::graph::ErrorResponse* Response::release_error() {
  // @@protoc_insertion_point(field_release:seegnify.graph.Response.error)
  if (_internal_has_error()) {
    clear_has_response();
      ::seegnify::graph::ErrorResponse* temp = response_.error_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    response_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::seegnify::graph::ErrorResponse& Response::_internal_error() const {
  return _internal_has_error()
      ? *response_.error_
      : *reinterpret_cast< ::seegnify::graph::ErrorResponse*>(&::seegnify::graph::_ErrorResponse_default_instance_);
}
inline const ::seegnify::graph::ErrorResponse& Response::error() const {
  // @@protoc_insertion_point(field_get:seegnify.graph.Response.error)
  return _internal_error();
}
inline ::seegnify::graph::ErrorResponse* Response::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_unsafe_arena_release:seegnify.graph.Response.error)
  if (_internal_has_error()) {
    clear_has_response();
    ::seegnify::graph::ErrorResponse* temp = response_.error_;
    response_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Response::unsafe_arena_set_allocated_error(::seegnify::graph::ErrorResponse* error) {
  clear_response();
  if (error) {
    set_has_error();
    response_.error_ = error;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:seegnify.graph.Response.error)
}
inline ::seegnify::graph::ErrorResponse* Response::_internal_mutable_error() {
  if (!_internal_has_error()) {
    clear_response();
    set_has_error();
    response_.error_ = CreateMaybeMessage< ::seegnify::graph::ErrorResponse >(GetArena());
  }
  return response_.error_;
}
inline ::seegnify::graph::ErrorResponse* Response::mutable_error() {
  // @@protoc_insertion_point(field_mutable:seegnify.graph.Response.error)
  return _internal_mutable_error();
}

inline bool Response::has_response() const {
  return response_case() != RESPONSE_NOT_SET;
}
inline void Response::clear_has_response() {
  _oneof_case_[0] = RESPONSE_NOT_SET;
}
inline Response::ResponseCase Response::response_case() const {
  return Response::ResponseCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace graph
}  // namespace seegnify

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_graph_2eproto
